# This file is the entry point to configure your own HTTP routes.
# Files in the routes/ subdirectory configure the routes for your dependencies.

#index:
#    path: /
#    defaults: { _controller: 'App\Controller\DefaultController::index' }

api.store-files:
  path: /api/images/store-files
  controller: 'App\Controller\ApiImageController::storeFile'
  methods: POST
api.store-from-remote-source:
  path: /api/images/store-from-remote-source
  controller: 'App\Controller\ApiImageController::saveFileFromUrl'
  methods: POST
api.store-from-base64:
  path: /api/images/store-from-base64
  controller: 'App\Controller\ApiImageController::saveFileFromBase64'
  methods: POST
api.test:
    path: /test
    controller: 'App\Controller\ApiImageController::testUpload'
    methods: GET
